apiVersion: 
kind: Deployment
metadata:
  name:springboot-secrets
  labels:
    app: springboot-secrets-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-secrets-app
  template:
    metadata:
      labels:
        app: springboot-secrets-app
    spec:
      containers:
      - name: springboot-secrets-app
        image: registry.hub.docker.com/kumarsaurabh/springboot-secrets-app:1.0
        ports:
        - containerPort: 8085
    - env:
          - name: SECRETS_DEMO_USER
            valueFrom:
              secretKeyRef:
                name: spring-security
                key: spring.user.name
          - name: SECRETS_DEMO_USER_PASSWD
            valueFrom:
              secretKeyRef:
                name: spring-security
                key: spring.user.password
          volumeMounts:
          - name: github-user 
            mountPath: "/deployments/github" 
            readOnly: true
      volumes:
      - name: github-user
        secret:
          secretName: spring-github-demo 
          items:
          - key: github.user 
            path: user 
          - key: github.token 
            path: token 