apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-secrets-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-secrets-fromenv-pod
  template:
    metadata:
      labels:
        app: springboot-secrets-fromenv-pod
    spec:
      containers:
        - name: springboot-secrets-fromenv-continer
          image: registry.hub.docker.com/kumarsaurabh/springboot-secrets-app:1.0
          imagePullPolicy: Always          
          ports:
            - containerPort: 8086
          env:
            - name: SECRETS_DEMO_USER
              valueFrom:
                secretKeyRef:
                  name: spring-security
                  key: spring.user.name
            - name: SECRETS_DEMO_USER_PASSWD
              valueFrom:
                secretKeyRef:
                  name: spring-security
                  key: spring.user.password
