apiVersion: v1
kind: Service
metadata:
  name: springboot-secrets-fromfile-service
spec:
  type: LoadBalancer
  selector:
    app: springboot-secrets-fromfile-pod
  ports:
  - name: http
    protocol: TCP
    port: 8086
    targetPort: 8086
    nodePort: 31363
    