apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-configmap-deployment
  labels:
    app: springboot-configmap-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-configmap-app
  template:
    metadata:
      labels:
        app: springboot-configmap-app
    spec:
      containers:
        - name: springboot-configmap-app
          image: registry.hub.docker.com/kumarsaurabh/springboot-configmap-app:1.0
          ports:
            - containerPort: 8085
          env:
            - name: GREETING_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: spring-boot-configmaps-demo
                  key: greeter.prefix
          volumeMounts:
            - name: application-config 
              mountPath: "/deployments/config" 
              readOnly: true
      volumes:
        - name: application-config
          configMap:
            name: spring-app-config 
            items:
              - key: application.properties 
                path: application.properties        