apiVersion: 
kind: Deployment
metadata:
  name:springboot-configmap
  labels:
    app: springboot-configmap-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-configmap-app
  template:
    metadata:
      labels:
        app: springboot-configmap-app
    spec:
      containers:
      - name: springboot-configmap-app
        image: registry.hub.docker.com/kumarsaurabh/springboot-configmap-app:1.0
        ports:
        - containerPort: 8085