apiVersion: v1
kind: Service
metadata:
  name: springboot-configmap-service
spec:
  type: LoadBalancer
  selector:
    app: springboot-configmap-app
  ports:
  - name: http
    protocol: TCP
    port: 8085
    targetPort: 8085
    nodePort: 31362
    